FROM node:18-alpine3.16

ENV DB_HOST=db-test
ENV DB_PORT=5432
ENV DB_NAME=postgres
ENV DB_USER=postgres
ENV DB_PASSWORD=postgres
ENV DB_MIN_POOL_SIZE=1
ENV DB_MAX_POOL_SIZE=2
ENV REDIS_HOST=cache-test
ENV REDIS_PORT=6379
ENV REDIS_USER=default
ENV REDIS_PASSWORD=nostr_ts_relay_test

WORKDIR /code

COPY ["package.json", "package-lock.json", "./"]

RUN npm install --quiet

CMD ["true"]
