FROM node:24-alpine

WORKDIR /code

COPY ["package.json", "pnpm-lock.yaml", "./"]

RUN corepack enable && corepack prepare pnpm@10.33.0 --activate && pnpm install --frozen-lockfile --silent

CMD ["true"]
