name: Changesets Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install package dependencies
        run: pnpm install --frozen-lockfile

      - run: git config user.name "github-actions[bot]"
      - run: git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: pnpm run changeset:version
          createGithubReleases: true
          title: "chore: release new version 🚀"
          commit: "chore: version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
