name: CI Checks

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install package dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
  build-check:
    name: Build check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install package dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run build:check
  test-units-and-cover:
    name: Unit Tests And Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install package dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test:unit
      - name: Run coverage for unit tests
        run: npm run cover:unit
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: ./.coverage/unit/lcov.info
          flag-name: Unit
          github-token: ${{ secrets.GITHUB_TOKEN }}
  test-integrations-and-cover:
    name: Integration Tests and Coverage
    runs-on: ubuntu-latest
    environment: test
    needs:
      - lint
      - build-check
      - test-units-and-cover
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Run integration tests
        run: npm run docker:test:integration
      - name: Run coverage for integration tests
        run: npm run docker:cover:integration
      - uses: deblockt/cucumber-report-annotations-action@v1.7
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: ".test-reports/integration/report.json"
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: ./.coverage/integration/lcov.info
          flag-name: Integration
          github-token: ${{ secrets.GITHUB_TOKEN }}