name: Checks

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install package dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install package dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run build
  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install package dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install package dependencies
        run: npm ci
      - name: Run coverage
        run: npm run cover
